###
### Komorniki MTB Team's config file
###

# Local URL
url: 'http://127.0.0.1:4000'
baseurl: ''

# Site
name: "Komorniki MTB Team"
title: "Komorniki MTB Team - zawsze w dobrym kierunku!"
description: "Oficjalna strona Komorniki MTB Team"
logo: 'assets/images/komornikimtb.png'
favicon: 'assets/images/favicon.ico'
umami_analytics: 'c92c2554-e27d-40ee-81bc-d8ab27eed691'
#google_analytics: 'UA-xxxxxxxx-1'
#disqus: 'demowebsite'
comments_disable: true
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
permalink: /:title/
excerpt_separator: "<!--more-->"
post_truncate: 40
email: web@komornikimtb.pl
locale: pl_PL

# Social
social:
  name: "Komorniki MTB Team"
  links:
    - https://www.facebook.com/Komorniki.MTB
    - https://www.instagram.com/komornikimtbteam
    - https://github.com/pablo-ross/komornikimtb

# KMTB resources
kmtb_facebook: "https://www.facebook.com/Komorniki.MTB/"
kmtb_instagram: "https://www.instagram.com/komornikimtbteam/"
kmtb_github: "https://github.com/pablo-ross/komornikimtb/"
kmtb_rss: "/feed.xml"

# Partners
partners:
  albeco:
    name: albeco
    display_name: Albeco
    logo: 'assets/partners/albeco.png'
    description: "Albeco to firma z ponad 30-letnim doświadczeniem, której zaufało ponad 10.000 odbiorców na całym świecie. Albeco od wielu lat dostarcza odbiorcom produkty najwyższej jakości w dziedzinie utrzymania ruchu."
    web: 'https://www.albeco.com.pl/'
  gatner:
    name: gatner
    display_name: Gatner Packaging
    logo: 'assets/partners/gatner.png'
    description: "Jedna z najnowocześniejszych linii produkcyjnych w Europie, która pozwala na produkcję nowoczesnych opakowań z tektury falistej."
    web: 'https://www.gatnerpackaging.pl/'
  gminakomorniki:
    name: gminakomorniki
    display_name: Gmina Komorniki
    logo: 'assets/partners/gmina-komorniki.png'
    description: "Gmina Komorniki aktywnie wspiera i współfinansuje nasze przedsięwzięcia z zakresu upowszechniania sportu wśród lokalnej społeczności gminnej."
    web: 'https://www.komorniki.pl/'
  gosirkomorniki:
    name: gosirkomorniki
    display_name: GOSiR Komorniki
    logo: 'assets/partners/gosir-komorniki.png'
    description: "GOSiR Komorniki - zanim struktury klubu zostały sformalizowane na papierze, od początku istnienia nieformalnej grupy rowerowej jest z nami GOSiR Komorniki."
    web: 'https://gosirkomorniki.pl/'
  grupacichyzasada:
    name: grupacichyzasada
    display_name: Grupa Cichy-Zasada
    logo: 'assets/partners/grupa-cichy-zasada.png'
    description: "Grupa Cichy-Zasada i marka Volkswagen Samochody Użytkowe udostępni zawodnikom klubu w użytkowanie pierwszy samochód - Volkswagen Caravelle."
    web: 'https://cichy-zasada.pl/'
  penco:
    name: penco
    display_name: Penco
    logo: 'assets/partners/penco.png'
    description: "Penco - paliwo dla sportu. Siedziba firmy znajduje się w Pradze w Czechach. Penco kładzie nacisk na bezpieczeństwo i wysoką jakość stosowanych składników."
    web: 'https://pencopolska.pl/'
  strefarowery:
    name: strefarowery
    display_name: Strefarowery.pl
    logo: 'assets/partners/strefa-rowery.png'
    description: "Strefarowery.pl to profesjonalny salon rowerowy z serwisem, szeroka gama akcesoriów rowerowych, autoryzowany serwis FOX, specjalistyczny i kompetentny serwis rowerowy."
    web: 'https://www.strefarowery.pl/'

# Authors
authors:
  ola:
    name: Ola
    display_name: Ola
    avatar: 'assets/avatars/av005.svg'
    description: "Redaktor tekstów i mediów dotyczących działalności Komorniki MTB Team."
  tomek:
    name: Tomek
    display_name: Tomek    
    avatar: 'assets/avatars/av002.svg'
    description: "Prezes klubu :)"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-leaflet
  - jekyll-minifier
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/kategoria/:name/'
    tag: '/tag/:name/'

# Collections
collections:
  strava_members:
    people: true
    output: true
    permalink: '/strava/:name/'

# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - docker-compose.yml
  - Gulpfile.js
  - package.json
  - package-lock.json
  - node_modules

include:
  - _pages

keep_files:
  - assets

# Minifier
jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)
    harmony: true
  exclude: ["robots.txt", "admin/config.yml", "feed.xml"]
